//==============================================================================
// Includes
//==============================================================================

#include <stdlib.h>
#include <string.h>

#include "swadge_esp32.h"
#include "swadgeMode.h"
#include "mode_credits.h"
#include "mode_main_menu.h"
#include "musical_buzzer.h"
#include "font.h"

//==============================================================================
// Defines
//==============================================================================

#define ABS(X) (((X) < 0) ? -(X) : (X))

//==============================================================================
// Functions Prototypes
//==============================================================================

void creditsEnterMode(display_t* disp);
void creditsExitMode(void);
void creditsMainLoop(int64_t elapsedUs);
void creditsButtonCb(buttonEvt_t* evt);

//==============================================================================
// Variables
//==============================================================================

typedef struct
{
    display_t* disp;
    font_t font;
    int64_t tElapsedUs;
    int8_t scrollMod;
    int16_t yOffset;
} credits_t;

credits_t* credits;

swadgeMode modeCredits =
{
    .modeName = "Credits",
    .fnEnterMode = creditsEnterMode,
    .fnExitMode = creditsExitMode,
    .fnMainLoop = creditsMainLoop,
    .fnButtonCallback = creditsButtonCb,
    .fnTouchCallback = NULL,
    .wifiMode = NO_WIFI,
    .fnEspNowRecvCb = NULL,
    .fnEspNowSendCb = NULL,
    .fnAccelerometerCallback = NULL,
    .fnAudioCallback = NULL,
    .fnTemperatureCallback = NULL,
    .overrideUsb = false
};

// Everyone's here
static const char* const creditNames[] =
{
    "Adam Feinstein\n",
    "Agnew\n",
    "Allison (AllieCat)", "Brantley\n",
    "Bedrock\n",
    "Bryce Browner\n",
    "Dac\n",
    "Dan 'Solo' Austin\n",
    "Decnav\n",
    "dylwhich\n",
    "Ellie (VanillyNeko.com)\n",
    "FuryfulFawful\n",
    "Greg Lord (@gplord)\n",
    "Grocery Man\n",
    "Haloflooder\n",
    "Hunter Dyar\n",
    "J.Vega (@JVeg199X)\n",
    "Joe Newman\n",
    "Jonathan Moriarty\n",
    "Kaitie Lawson\n",
    "Kevin \"PF3k\" Lin\n",
    "Laurel Lemon\n",
    "Max Campbell\n",
    "MrTroy\n",
    "Private Island\n",
    "Thaeli\n",
    "",
    "",
};

// Must be same length as creditNames
static const paletteColor_t creditColors[] =
{
    c031,
    c530,
    c423, c423,
    c520,
    c115,
    c545,
    c315,
    c325,
    c035,
    c324,
    c452,
    c035,
    c505,
    c500,
    c445,
    c250,
    c255,
    c315,
    c540,
    c205,
    c235,
    c113,
    c234,
    c114,
    c015,
    c000,
    c000,
};

const song_t creditsSong =
{
    .notes =
    {
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = D_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = B_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = A_3, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = A_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = G_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = B_3, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 28},
        {.note = G_4, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 461},
        {.note = G_7, .timeMs = 28},
        {.note = F_SHARP_7, .timeMs = 28},
        {.note = F_7, .timeMs = 28},
        {.note = E_7, .timeMs = 28},
        {.note = D_SHARP_7, .timeMs = 28},
        {.note = D_7, .timeMs = 28},
        {.note = C_SHARP_7, .timeMs = 28},
        {.note = C_7, .timeMs = 28},
        {.note = B_6, .timeMs = 28},
        {.note = A_SHARP_6, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = G_SHARP_6, .timeMs = 28},
        {.note = G_6, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = F_6, .timeMs = 28},
        {.note = E_6, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_3, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_4, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_4, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 259},
        {.note = SILENCE, .timeMs = 86},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = A_3, .timeMs = 259},
        {.note = SILENCE, .timeMs = 86},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = G_3, .timeMs = 259},
        {.note = SILENCE, .timeMs = 86},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = E_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = F_SHARP_3, .timeMs = 259},
        {.note = SILENCE, .timeMs = 86},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = B_2, .timeMs = 115},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_2, .timeMs = 115},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = A_2, .timeMs = 115},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_2, .timeMs = 115},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = G_2, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_2, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = E_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = F_SHARP_2, .timeMs = 115},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_2, .timeMs = 115},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 144},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 144},
        {.note = SILENCE, .timeMs = 86},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_3, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_4, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = A_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = E_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 28},
        {.note = A_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_6, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_2, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_5, .timeMs = 28},
        {.note = F_SHARP_6, .timeMs = 28},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_3, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_4, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = F_SHARP_6, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
        {.note = C_SHARP_4, .timeMs = 57},
        {.note = SILENCE, .timeMs = 57},
    },
    .numNotes = 1581,
    .shouldLoop = true
};

//==============================================================================
// Functions
//==============================================================================

/**
 * Enter the credits mode, allocate and initialize memory
 */
void creditsEnterMode(display_t* disp)
{
    // Allocate memory for this mode
    credits = (credits_t*)calloc(1, sizeof(credits_t));

    // Save a pointer to the display
    credits->disp = disp;

    // Load some fonts
    loadFont("mm.font", &credits->font);

    // Set initial variables
    credits->yOffset = disp->h;
    credits->tElapsedUs = 0;
    credits->scrollMod = 1;

    buzzer_play_bgm(&creditsSong);
}

/**
 * Exit the credits mode, free memory
 */
void creditsExitMode(void)
{
    freeFont(&credits->font);
    free(credits);
}

/**
 * Main credits loop, draw some scrolling credits
 *
 * @param elapsedUs The time elapsed since the last call
 */
void creditsMainLoop(int64_t elapsedUs)
{
    credits->tElapsedUs += elapsedUs;

    // If enough time has passed, translate and redraw text
    uint32_t updateTime = 100000 / ABS(credits->scrollMod);
    if(credits->tElapsedUs > updateTime)
    {
        credits->tElapsedUs -= updateTime;

        // This static var tracks the vertical scrolling offset
        credits->yOffset -= (credits->scrollMod > 0) ? 1 : -1;

        // Clear first
        credits->disp->clearPx();

        // Draw names until the cursor is off the screen
        int16_t yPos = 0;
        int16_t idx = 0;
        while((yPos + credits->yOffset) < credits->disp->h)
        {
            // Only draw names with negative offsets if they're a little on screen
            if((yPos + credits->yOffset) >= -credits->font.h)
            {
                // If the names have scrolled back to the start, reset the scroll vars
                if(0 == (yPos + credits->yOffset) && 0 == idx)
                {
                    credits->yOffset = 0;
                    yPos = 0;
                }

                // Center and draw the text
                int16_t tWidth = textWidth(&credits->font, creditNames[idx]);
                drawText(credits->disp, &credits->font, creditColors[idx], creditNames[idx],
                         (credits->disp->w - tWidth) / 2, (yPos + credits->yOffset));
            }

            // Add more space if the credits end in a newline
            size_t nameLen = strlen(creditNames[idx]);
            if((nameLen > 0) && ('\n' == creditNames[idx][nameLen - 1]))
            {
                yPos += credits->font.h + 8;
            }
            else
            {
                yPos += credits->font.h + 1;
            }

            // Always update the idx and cursor position, even if the text wasn't drawn
            idx = (idx + 1) % ARRAY_SIZE(creditNames);
        }
    }
}

/**
 * @brief Credits button callback, either speed up, reverse, or exit credits
 *
 * @param evt The button event
 */
void creditsButtonCb(buttonEvt_t* evt)
{
    if(evt->down)
    {
        switch (evt->button)
        {
            case UP:
            {
                // Scroll faster
                credits->scrollMod = 4;
                break;
            }
            case DOWN:
            {
                // Scroll faster, backwards
                credits->scrollMod = -4;
                break;
            }
            case BTN_A:
            case BTN_B:
            {
                // Exit
                switchToSwadgeMode(&modeMainMenu);
                break;
            }
            case LEFT:
            case RIGHT:
            case START:
            case SELECT:
            {
                break;
            }
        }
    }
    else
    {
        switch (evt->button)
        {
            case UP:
            case DOWN:
            {
                // Resume normal scrolling
                credits->scrollMod = 1;
                break;
            }
            case BTN_A:
            case BTN_B:
            case LEFT:
            case RIGHT:
            case START:
            case SELECT:
            {
                // Do nothing
                break;
            }
        }
    }
}
