#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <unistd.h>
#include <ftw.h>

#include "spiffs_file_preprocessor.h"
#include "image_processor.h"

const char * inDirName = NULL;
const char * outDirName = NULL;

/**
 * @brief TODO
 *
 */
void print_usage(void)
{
    printf("Usage:\n  spiffs_file_preprocessor\n    -i INPUT_DIRECTORY\n    -o OUTPUT_DIRECTORY\n");
}

/**
 * @brief Get the filename ext object
 *
 * @param filename
 * @return const char*
 */
const char *get_filename_ext(const char *filename) {
    const char *dot = strrchr(filename, '.');
    if(!dot || dot == filename) {
        return "";
    }
    return dot + 1;
}

/**
 * @brief Get the filename ext object
 *
 * @param filename
 * @return const char*
 */
const char *get_filename(const char *filename) {
    const char *slash = strrchr(filename, '/');
    if(!slash || slash == filename) {
        return "";
    }
    return slash + 1;
}

/**
 * @brief TODO
 *
 * @param fpath
 * @param st
 * @param tflag
 * @return int
 */
static int display_info(const char * fpath, const struct stat * st __attribute__((unused)), int tflag)
{
    switch(tflag) {
    case FTW_F: // file
    {
        if(0 == strcmp("png", get_filename_ext(fpath)))
        {
            process_image(fpath, outDirName);
        }
        break;
    }
    case FTW_D: // directory
    {
        break;
    }
    case FTW_SL: // symlink
    {
        return -1;
    }
    case FTW_NS: // failed
    {
        return -1;
    }
    case FTW_DNR: // failed
    {
        return -1;
    }
    }
    return 0;
}

/**
 * @brief TODO
 *
 * @param argc
 * @param argv
 * @return int
 */
int main(int argc, char ** argv)
{
    int c;

    opterr = 0;
    while ((c = getopt (argc, argv, "i:o:")) != -1)
    {
        switch (c)
        {
        case 'i': {
            inDirName = optarg;
            break;
        }
        case 'o': {
            outDirName = optarg;
            break;
        }
        default: {
            fprintf(stderr, "Invalid argument %c\n", c);
            print_usage();
            return -1;
        }
        }
    }

    if(NULL == inDirName || NULL == outDirName)
    {
        fprintf(stderr, "Failed to provide all arguments\n");
        print_usage();
        return -1;
    }

    if(ftw(inDirName, display_info, 99) == -1) {
        fprintf(stderr, "Failed to walk file tree\n");
        return -1;
    }

    // char testFilePath[128] = {0};
    // strcat(testFilePath, outDirName);
    // strcat(testFilePath, "autogen.txt");

    // FILE * fp = fopen(testFilePath, "wb+");
    // char example[] = "autogenerated file";
    // fwrite(example, strlen(example), 1, fp);
    // fclose(fp);

    return 0;
}
