#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>
#include <unistd.h>

void print_usage(void)
{
    printf("Usage:\n  spiffs_file_preprocessor\n    -i INPUT_DIRECTORY\n    -o OUTPUT_DIRECTORY\n");
}

int main(int argc, char ** argv)
{
    char * inDirName = NULL;
    char * outDirName = NULL;
    int c;

    opterr = 0;
    while ((c = getopt (argc, argv, "i:o:")) != -1)
    {
        switch (c)
        {
        case 'i': {
            inDirName = optarg;
            break;
        }
        case 'o': {
            outDirName = optarg;
            break;
        }
        default: {
            print_usage();
            return -1;
        }
        }
    }

    if(NULL == inDirName || NULL == outDirName)
    {
        print_usage();
        return -1;
    }

    char testFilePath[128] = {0};
    strcat(testFilePath, outDirName);
    strcat(testFilePath, "autogen.txt");

    FILE * fp = fopen(testFilePath, "wb+");
    char example[] = "autogenerated file";
    fwrite(example, strlen(example), 1, fp);
    fclose(fp);

    return 0;
}
