#ifndef _MODE_PLATFORMER_H_
#define _MODE_PLATFORMER_H_
//==============================================================================
// Includes
//==============================================================================
#include "common_typedef.h"

/*==============================================================================
 * Defines
 *============================================================================*/

#define NUM_PLATFORMER_HIGH_SCORES 5

//==============================================================================
// Constants
//==============================================================================

static const song_t bgmDemagio =
{
    .notes =
    {
        {.note = A_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_2, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_2, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = D_2, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_2, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_3, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_4, .timeMs = 187},
        {.note = G_2, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = C_5, .timeMs = 179},

    },
    .numNotes = 289,
    .shouldLoop = true
};

static const song_t bgmIntro =
{
    .notes =
    {
        {C_SHARP_5, 130},
        {C_SHARP_3, 62},
        {SILENCE, 67},
        {A_3, 62},
        {SILENCE, 67},
        {E_4, 62},
        {SILENCE, 67},
        {A_4, 130},
        {C_SHARP_5, 130},
        {D_5, 130},
        {C_3, 62},
        {SILENCE, 67},
        {A_3, 62},
        {SILENCE, 67},
        {E_4, 67},
        {SILENCE, 62},
        {A_4, 130},
        {D_5, 130},
        {E_5, 130},
        {B_4, 130},
        {A_4, 130},
        {E_4, 130},
        {B_3, 83},
        {A_3, 78},
        {E_3, 78},
        {B_2, 83},
        {E_2, 317}
    },
    .numNotes = 27,
    .shouldLoop = false
};

static const song_t bgmSmooth =
{
    .notes =
    {
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = C_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = D_6, .timeMs = 46},
        {.note = D_SHARP_6, .timeMs = 140},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = D_SHARP_6, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 93},
        {.note = SILENCE, .timeMs = 46},
        {.note = C_4, .timeMs = 46},
        {.note = SILENCE, .timeMs = 46},
        {.note = C_4, .timeMs = 46},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = C_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 93},
        {.note = F_4, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 93},
        {.note = C_SHARP_5, .timeMs = 93},
        {.note = C_4, .timeMs = 93},
        {.note = D_SHARP_4, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 93},
        {.note = C_5, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = D_SHARP_4, .timeMs = 93},
        {.note = G_4, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 93},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = C_6, .timeMs = 187},
        {.note = D_SHARP_6, .timeMs = 187},
        {.note = F_6, .timeMs = 46},
        {.note = E_6, .timeMs = 23},
        {.note = D_SHARP_6, .timeMs = 23},
        {.note = C_SHARP_6, .timeMs = 23},
        {.note = C_6, .timeMs = 23},
        {.note = A_5, .timeMs = 23},
        {.note = G_5, .timeMs = 23},
        {.note = F_SHARP_5, .timeMs = 23},
        {.note = E_5, .timeMs = 23},
        {.note = D_SHARP_5, .timeMs = 23},
        {.note = C_SHARP_5, .timeMs = 23},
        {.note = C_5, .timeMs = 23},
        {.note = A_4, .timeMs = 23},
        {.note = G_4, .timeMs = 23},
        {.note = F_SHARP_4, .timeMs = 19},

    },
    .numNotes = 425,
    .shouldLoop = true
};

//==============================================================================
// Structs
//==============================================================================

typedef struct {
    uint32_t scores[NUM_PLATFORMER_HIGH_SCORES];
    char initials[NUM_PLATFORMER_HIGH_SCORES][3];
} platformerHighScores_t;

//==============================================================================
// Prototypes
//==============================================================================

void updateGame(platformer_t *platformer);
void updateTitleScreen(platformer_t *platformer);

extern swadgeMode modePlatformer;

#endif
