//==============================================================================
// Includes
//==============================================================================

#include "platformer_sounds.h"

//==============================================================================
// Constants
//==============================================================================

//by FuryfulFawful
const song_t bgmDemagio =
{
    .notes =
    {
        {.note = A_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_2, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_2, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = E_5, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = C_SHARP_5, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_3, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = D_2, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_2, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_3, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_4, .timeMs = 187},
        {.note = G_2, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = A_4, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = B_4, .timeMs = 187},
        {.note = C_5, .timeMs = 179},

    },
    .numNotes = 289,
    .shouldLoop = true
};

const song_t bgmIntro =
{
    .notes =
    {
        {C_SHARP_5, 130},
        {C_SHARP_3, 62},
        {SILENCE, 67},
        {A_3, 62},
        {SILENCE, 67},
        {E_4, 62},
        {SILENCE, 67},
        {A_4, 130},
        {C_SHARP_5, 130},
        {D_5, 130},
        {C_3, 62},
        {SILENCE, 67},
        {A_3, 62},
        {SILENCE, 67},
        {E_4, 67},
        {SILENCE, 62},
        {A_4, 130},
        {D_5, 130},
        {E_5, 130},
        {B_4, 130},
        {A_4, 130},
        {E_4, 130},
        {B_3, 83},
        {A_3, 78},
        {E_3, 78},
        {B_2, 83},
        {E_2, 317}
    },
    .numNotes = 27,
    .shouldLoop = false
};

//by Bedrock
const song_t bgmSmooth =
{
    .notes =
    {
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = C_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = D_6, .timeMs = 46},
        {.note = D_SHARP_6, .timeMs = 140},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_5, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_4, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = D_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = C_6, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_5, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = SILENCE, .timeMs = 187},
        {.note = A_SHARP_2, .timeMs = 187},
        {.note = D_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = D_SHARP_6, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 140},
        {.note = B_3, .timeMs = 46},
        {.note = C_4, .timeMs = 93},
        {.note = SILENCE, .timeMs = 46},
        {.note = C_4, .timeMs = 46},
        {.note = SILENCE, .timeMs = 46},
        {.note = C_4, .timeMs = 46},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = C_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_4, .timeMs = 117},
        {.note = SILENCE, .timeMs = 70},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 140},
        {.note = SILENCE, .timeMs = 46},
        {.note = F_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_3, .timeMs = 39},
        {.note = SILENCE, .timeMs = 54},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 93},
        {.note = F_4, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 93},
        {.note = C_SHARP_5, .timeMs = 93},
        {.note = C_4, .timeMs = 93},
        {.note = D_SHARP_4, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 93},
        {.note = C_5, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 93},
        {.note = D_SHARP_4, .timeMs = 93},
        {.note = G_4, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 93},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = G_5, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_4, .timeMs = 187},
        {.note = F_6, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_4, .timeMs = 187},
        {.note = F_3, .timeMs = 187},
        {.note = G_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = A_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = A_SHARP_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = F_5, .timeMs = 93},
        {.note = SILENCE, .timeMs = 93},
        {.note = C_6, .timeMs = 187},
        {.note = D_SHARP_6, .timeMs = 187},
        {.note = F_6, .timeMs = 46},
        {.note = E_6, .timeMs = 23},
        {.note = D_SHARP_6, .timeMs = 23},
        {.note = C_SHARP_6, .timeMs = 23},
        {.note = C_6, .timeMs = 23},
        {.note = A_5, .timeMs = 23},
        {.note = G_5, .timeMs = 23},
        {.note = F_SHARP_5, .timeMs = 23},
        {.note = E_5, .timeMs = 23},
        {.note = D_SHARP_5, .timeMs = 23},
        {.note = C_SHARP_5, .timeMs = 23},
        {.note = C_5, .timeMs = 23},
        {.note = A_4, .timeMs = 23},
        {.note = G_4, .timeMs = 23},
        {.note = F_SHARP_4, .timeMs = 19},

    },
    .numNotes = 425,
    .shouldLoop = true
};

//gmcc_underground by Bedrock
const song_t bgmUnderground =
{
    .notes =
    {
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = G_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 115},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 115},
        {.note = F_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 115},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 115},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = G_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 115},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 115},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 115},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 115},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = G_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = F_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = G_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = D_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = F_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = A_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = A_6, .timeMs = 19},
        {.note = A_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = B_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 19},
        {.note = SILENCE, .timeMs = 19},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = B_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_5, .timeMs = 115},
        {.note = D_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = D_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 115},
        {.note = C_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 115},
        {.note = C_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_5, .timeMs = 115},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = F_5, .timeMs = 115},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_4, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_4, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_4, .timeMs = 19},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = F_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 115},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = F_5, .timeMs = 115},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_5, .timeMs = 115},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_4, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_6, .timeMs = 19},
        {.note = C_5, .timeMs = 96},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_6, .timeMs = 19},
        {.note = C_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 96},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_6, .timeMs = 19},
        {.note = D_5, .timeMs = 96},
        {.note = D_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = D_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_4, .timeMs = 96},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_5, .timeMs = 19},
        {.note = G_4, .timeMs = 96},
        {.note = C_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_5, .timeMs = 19},
        {.note = A_SHARP_4, .timeMs = 96},
        {.note = C_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_6, .timeMs = 19},
        {.note = C_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_6, .timeMs = 19},
        {.note = C_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = G_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = C_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 96},
        {.note = F_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 96},
        {.note = A_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 96},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = G_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = F_4, .timeMs = 86},
        {.note = SILENCE, .timeMs = 48},
        {.note = A_SHARP_4, .timeMs = 38},
        {.note = A_SHARP_4, .timeMs = 38},
        {.note = A_SHARP_4, .timeMs = 38},
        {.note = A_SHARP_4, .timeMs = 96},
        {.note = A_SHARP_6, .timeMs = 19},
        {.note = A_SHARP_5, .timeMs = 96},
        {.note = SILENCE, .timeMs = 115},
        {.note = G_6, .timeMs = 19},
        {.note = G_5, .timeMs = 96},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = SILENCE, .timeMs = 115},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = F_6, .timeMs = 19},
        {.note = F_5, .timeMs = 96},
        {.note = SILENCE, .timeMs = 115},
        {.note = D_SHARP_6, .timeMs = 19},
        {.note = D_SHARP_5, .timeMs = 96},
        {.note = D_SHARP_3, .timeMs = 86},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = D_SHARP_4, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = G_3, .timeMs = 201},
        {.note = SILENCE, .timeMs = 28},
        {.note = A_SHARP_3, .timeMs = 201},

    },
    .numNotes = 884,
    .shouldLoop = true
};

const song_t bgmCastle =
{
    .notes =
    {
        {.note = D_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = E_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 441},
        {.note = D_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 441},
        {.note = D_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = E_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 441},
        {.note = D_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_5, .timeMs = 88},
        {.note = D_5, .timeMs = 88},
        {.note = D_SHARP_5, .timeMs = 88},
        {.note = F_5, .timeMs = 88},
        {.note = F_SHARP_5, .timeMs = 88},
        {.note = G_SHARP_5, .timeMs = 88},
        {.note = A_5, .timeMs = 88},
        {.note = B_5, .timeMs = 88},
        {.note = C_SHARP_6, .timeMs = 352},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = E_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_6, .timeMs = 352},
        {.note = A_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = B_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_5, .timeMs = 88},
        {.note = D_5, .timeMs = 88},
        {.note = D_SHARP_5, .timeMs = 88},
        {.note = F_5, .timeMs = 88},
        {.note = F_SHARP_5, .timeMs = 88},
        {.note = G_SHARP_5, .timeMs = 88},
        {.note = A_5, .timeMs = 88},
        {.note = B_5, .timeMs = 88},
        {.note = G_SHARP_5, .timeMs = 352},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_6, .timeMs = 352},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = A_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = C_SHARP_3, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_2, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_3, .timeMs = 88},
        {.note = SILENCE, .timeMs = 88},
        {.note = G_SHARP_3, .timeMs = 88},
        {.note = SILENCE, .timeMs = 88},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 352},
        {.note = G_SHARP_2, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = D_SHARP_4, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = G_SHARP_6, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = D_SHARP_5, .timeMs = 176},
        {.note = D_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 352},
        {.note = G_SHARP_2, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = D_SHARP_4, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = D_SHARP_5, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 352},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 352},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_6, .timeMs = 352},
        {.note = D_SHARP_6, .timeMs = 352},
        {.note = G_5, .timeMs = 352},
        {.note = A_SHARP_5, .timeMs = 352},
        {.note = D_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_4, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = D_SHARP_5, .timeMs = 176},
        {.note = F_SHARP_5, .timeMs = 176},
        {.note = A_SHARP_5, .timeMs = 176},
        {.note = G_SHARP_5, .timeMs = 352},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = D_SHARP_5, .timeMs = 176},
        {.note = D_5, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = E_3, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = E_3, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_4, .timeMs = 352},
        {.note = D_SHARP_3, .timeMs = 352},
        {.note = G_3, .timeMs = 352},
        {.note = D_SHARP_4, .timeMs = 352},
        {.note = C_5, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = E_3, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = E_3, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 352},
        {.note = D_5, .timeMs = 352},
        {.note = D_SHARP_5, .timeMs = 352},
        {.note = SILENCE, .timeMs = 352},
        {.note = C_5, .timeMs = 44},
        {.note = C_6, .timeMs = 44},
        {.note = C_5, .timeMs = 44},
        {.note = C_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_5, .timeMs = 44},
        {.note = C_6, .timeMs = 44},
        {.note = C_5, .timeMs = 44},
        {.note = C_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_5, .timeMs = 44},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_3, .timeMs = 44},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_5, .timeMs = 44},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_3, .timeMs = 44},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 44},
        {.note = G_SHARP_5, .timeMs = 44},
        {.note = G_SHARP_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 44},
        {.note = E_3, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 44},
        {.note = G_SHARP_5, .timeMs = 44},
        {.note = G_SHARP_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 44},
        {.note = E_3, .timeMs = 176},
        {.note = G_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = G_4, .timeMs = 44},
        {.note = G_5, .timeMs = 44},
        {.note = G_4, .timeMs = 44},
        {.note = G_3, .timeMs = 44},
        {.note = G_4, .timeMs = 44},
        {.note = G_3, .timeMs = 44},
        {.note = G_4, .timeMs = 44},
        {.note = G_3, .timeMs = 44},
        {.note = D_SHARP_3, .timeMs = 352},
        {.note = G_3, .timeMs = 352},
        {.note = D_SHARP_4, .timeMs = 352},
        {.note = C_5, .timeMs = 44},
        {.note = C_6, .timeMs = 44},
        {.note = C_5, .timeMs = 44},
        {.note = C_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_5, .timeMs = 44},
        {.note = C_6, .timeMs = 44},
        {.note = C_5, .timeMs = 44},
        {.note = C_4, .timeMs = 44},
        {.note = G_SHARP_3, .timeMs = 176},
        {.note = C_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_5, .timeMs = 44},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_3, .timeMs = 44},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_5, .timeMs = 44},
        {.note = A_SHARP_4, .timeMs = 44},
        {.note = A_SHARP_3, .timeMs = 44},
        {.note = F_SHARP_3, .timeMs = 176},
        {.note = A_SHARP_4, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 44},
        {.note = C_SHARP_6, .timeMs = 44},
        {.note = C_SHARP_5, .timeMs = 44},
        {.note = C_SHARP_4, .timeMs = 44},
        {.note = E_3, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 44},
        {.note = C_SHARP_6, .timeMs = 44},
        {.note = C_SHARP_5, .timeMs = 44},
        {.note = C_SHARP_4, .timeMs = 44},
        {.note = E_3, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 176},
        {.note = SILENCE, .timeMs = 176},
        {.note = C_SHARP_5, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_5, .timeMs = 264},
        {.note = SILENCE, .timeMs = 88},
        {.note = D_SHARP_5, .timeMs = 352},

    },
    .numNotes = 334,
    .shouldLoop = true
};

const song_t sndGameStart =
{
    .notes =
    {
        {C_4, 50},{SILENCE, 50},{C_4, 100},{SILENCE, 200},{C_5, 100},
        {SILENCE, 100},{E_4, 100},{SILENCE, 100},{E_4, 100},{SILENCE, 100},
        {G_4, 100},{C_5, 100},{SILENCE, 100},{G_4, 100}
    },
    .numNotes = 14,
    .shouldLoop = false
};

const song_t sndDie =
{
    .notes =
    {
        {C_SHARP_5, 100},{A_SHARP_4, 100},{G_SHARP_4, 200},{F_SHARP_4, 100},
        {D_SHARP_4, 100},{SILENCE, 100},{D_4, 100},{SILENCE, 100},
        {C_SHARP_4, 100}
    },
    .numNotes = 9,
    .shouldLoop = false
};

const song_t sndMenuSelect =
{
    .notes =
    {
        {C_5, 50},{C_4, 50}
    },
    .numNotes = 2,
    .shouldLoop = false
};

const song_t sndMenuConfirm =
{
    .notes =
    {
        {C_6, 50},{C_5, 50},{C_4, 50}
    },
    .numNotes = 2,
    .shouldLoop = false
};

const song_t sndMenuDeny =
{
    .notes =
    {
        {C_3, 50},{SILENCE, 50},{C_3, 50}
    },
    .numNotes = 3,
    .shouldLoop = false
};

const song_t sndPause =
{
    .notes = 
    {
        {G_6, 80},{E_6, 80},{G_6, 80},{E_6, 80}
    },
    .numNotes = 4,
    .shouldLoop = false
};

const song_t sndHit =
    {
        .notes =
            {
                {C_4, 25}, {C_5, 25}},
        .numNotes = 2,
        .shouldLoop = false
    };

const song_t sndSquish =
    {
        .notes =
            {
                {740, 10}, {840, 10}, {940, 10}},
        .numNotes = 3,
        .shouldLoop = false
    };

const song_t sndBreak =
    {
        .notes =
            {
                {C_5, 25}, {C_4, 25}, {A_4, 25}, {A_SHARP_3, 25}, {A_3, 25}},
        .numNotes = 5,
        .shouldLoop = false
    };

const song_t sndCoin =
    {
        .notes =
            {
                {1000, 50}, {1200, 100}},
        .numNotes = 2,
        .shouldLoop = false
    };

const song_t sndPowerUp =
    {
        .notes =
            { 
                {C_4, 100}, {G_4, 100}, {E_4, 100}, {C_5, 100}, {G_4, 100}, {D_5, 100}, {C_5, 100}},
        .numNotes = 7,
        .shouldLoop = false
    };

const song_t sndJump1 =
    {
        .notes =
            { 
                {C_5, 50}, {E_5, 50}, {C_5, 50}},
        .numNotes = 2,
        .shouldLoop = false
    };         

const song_t sndJump2 =
    {
        .notes =
            { 
                {E_5, 50}, {G_5, 50}, {E_5, 50}},
        .numNotes = 2,
        .shouldLoop = false
    };         

const song_t sndJump3 =
    {
        .notes =
            { 
                {G_5, 50}, {C_6, 50}, {G_5, 50}},
        .numNotes = 2,
        .shouldLoop = false
    };

const song_t sndWarp =
    {
        .notes =
            { 
                {D_5, 50}, {A_4, 50}, {E_4, 50},{D_5, 50}, {A_4, 50}, {E_4, 50},{D_5, 50}, {A_4, 50}, {E_4, 50}
            },
        .numNotes = 9,
        .shouldLoop = false
    };

const song_t sndHurt =
    {
        .notes =
            { 
                {E_4, 50}, {D_SHARP_4, 50}, {D_4, 50},{C_SHARP_4, 50}, {C_4, 50}, {C_5, 50}, {C_4, 50}
            },
        .numNotes = 6,
        .shouldLoop = false
    };   

const song_t sndWaveBall =
{
    .notes =
    {
        {D_4, 50},{D_5, 50},{A_6, 50},{A_5, 50}
    },
    .numNotes = 4,
    .shouldLoop = false
};    

const song_t snd1up =
{
    .notes = 
    {
        {G_7, 80},{D_6, 80},{B_5, 120}
    },
    .numNotes = 3,
    .shouldLoop = false
};

const song_t sndCheckpoint =
{
    .notes = 
    {
        {C_6, 80},{A_5, 120}
    },
    .numNotes = 2,
    .shouldLoop = false
};

const song_t sndLevelClearD =
{
    .notes = 
    {
        {C_4, 100},{E_4, 100},{G_4, 100},{C_5, 200}
    },
    .numNotes = 4,
    .shouldLoop = false
};

const song_t sndLevelClearC =
{
    .notes = 
    {
        {E_4, 100},{G_4, 100},{C_5, 100},{E_5, 200}
    },
    .numNotes = 4,
    .shouldLoop = false
};

const song_t sndLevelClearB =
{
    .notes = 
    {
        {C_4, 100},{E_4, 100},{G_4, 100},{E_4, 100},{C_5, 100},{E_5, 100},{C_5, 200}
    },
    .numNotes = 7,
    .shouldLoop = false
};

const song_t sndLevelClearA =
{
    .notes = 
    {
        {C_4, 100},{E_4, 100},{G_4, 100},{E_4, 100},{C_5, 100},{E_5, 100},{C_5, 100},{B_4, 100},{D_5, 100},{G_5, 200}
    },
    .numNotes = 10,
    .shouldLoop = false
};

const song_t sndLevelClearS =
{
    .notes = 
    {
        {C_4, 100},{E_4, 100},{G_4, 100},{E_4, 100},{C_5, 100},{E_5, 100},{C_5, 100},{B_4, 100},{D_5, 100},{G_5, 100},{D_5, 100},{C_6, 100},{E_6, 100},{D_6, 200}
    },
    .numNotes = 14,
    .shouldLoop = false
};

const song_t sndTally =
{
    .notes = 
    {
        {C_7, 8}
    },
    .numNotes = 1,
    .shouldLoop = false
};

const song_t bgmNameEntry =
{
    .notes = 
    {
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = C_SHARP_3, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = G_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_SHARP_3, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_3, .timeMs = 187},
        {.note = A_3, .timeMs = 187},
        {.note = B_2, .timeMs = 187},
        {.note = B_3, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = G_3, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = G_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = D_4, .timeMs = 187},
        {.note = E_2, .timeMs = 187},
        {.note = F_SHARP_4, .timeMs = 187},
        {.note = A_2, .timeMs = 187},
        {.note = E_4, .timeMs = 187},
        {.note = C_SHARP_4, .timeMs = 187},
        {.note = G_SHARP_2, .timeMs = 187},
        {.note = D_SHARP_4, .timeMs = 187},
        {.note = C_4, .timeMs = 187},
        {.note = G_2, .timeMs = 187},
        {.note = D_4, .timeMs = 187}
    },
    .numNotes = 64,
    .shouldLoop = true
};

const song_t bgmGameOver =
{
    .notes = 
    {
        {A_SHARP_6, 80},
        {B_6, 80},
        {C_7, 80},
        {SILENCE, 80},
        {F_6, 80},
        {F_SHARP_6, 80},
        {G_6, 80},
        {SILENCE, 80},
        {D_6, 80},
        {D_SHARP_6, 80},
        {E_6, 80},
        {C_6, 160}
    },
    .numNotes = 12,
    .shouldLoop = false
};

const song_t sndOuttaTime=
{
    .notes = 
    {
        {C_6, 80},
        {D_SHARP_6, 80},
        {F_SHARP_6, 80},
        {SILENCE, 80}
    },
    .numNotes = 4,
    .shouldLoop = true
};
